### ISSUE TITLE
Keyfinder folder missing?

### ISSUE THREAD

**Issue by DELTAJoSch** [ibsh/is_KeyFinder#105]
When I open your Project in QT and try to compile it, there are errors due to missing files in a folder called keyfinder (e.g.: #include "keyfinder/keyfinder.h"). Am I just too dumb or is it really missing?

**Comment by ibsh** [comment]
Been a while since I’ve looked at this but I’d guess you’re missing the dependency libKeyFinder, where the algorithm lives.
