### ISSUE TITLE
Windows MSVC Build 2.3 

### ISSUE THREAD

**Issue by lurumdare** [ibsh/is_KeyFinder#106]
I build latest version.
If anyone needs.

Good idea - add to releases.

[Mega](https://mega.nz/#!rUMBlY6K!Vy13mXejCWXZIOAGncHLV2aaKqIw-UxXWOE0UztdBH0)

**Comment by daslicht** [comment]
I get libeay32 missing , idea?

**Comment by jaspergould** [comment]
@daslicht download from google.

**Comment by daslicht** [comment]
I did but then i get another error...

**Comment by jaspergould** [comment]
@daslicht maybe rename .dll !? Remove MD.

**Comment by cyberfunk** [comment]
Hi guys! Thanks for he update. I can't get this working in Windows 10 October update. It won't write any values to my tags. I had the same problem with old version 1.25 and thought this update would solve my issues. Any tips on getting this working. If I run it in administrator mode it will not allow me to drag and drop any files. I checked and my files are not read only but I should mention all of my folders have a square not a check next to "Read Only" in Windows folder security properties. Not sure if that is the cause of the problem. All my other programs can read and write to files and folders so I'm stumped.

**Comment by galaxy-nomad** [comment]
Hi guys thanks for compiling version 2.3 for Windows. Unfortunately this version is not as accurate as old 1.25 for some reason. When I analyze my files it leaves a lot of them with three dots ... like it can't figure out the key for those files. 1.25 get's them all. Is there an explanation for this behavior with 2.3?

**Comment by ozone1979** [comment]
Can someone please address cyberfunks issue?
Also, I'm guessing that changes for version 2.4 are only applicable macOS .

**Comment by daslicht** [comment]
anyone keep maintaining the windows version ?

**Comment by dking2011** [comment]
> Hi guys thanks for compiling version 2.3 for Windows. Unfortunately this version is not as accurate as old 1.25 for some reason. When I analyze my files it leaves a lot of them with three dots ... like it can't figure out the key for those files. 1.25 get's them all. Is there an explanation for this behavior with 2.3?

I also want to thank you for compiling this version, but comparing between this and 1.25 give wildly different results.

Of my selection of 95 songs:

 • 20 did not find a key
 • none of them achieved the same key as the previous version
 • only two were output with keys higher than 06B, with 06B and 01B being the most popular by far

This also appears to be around five times slower. I started timing at 20% of my selection and it completed in another 1 minute 49 seconds. The same selection took 32 seconds from start to finish.

Something seems very off with this version - sorry!
