### ISSUE TITLE
Ogg-Vorbis: Comment tag is written as 'description' tag

### ISSUE THREAD

**Issue by herrsimon** [ibsh/is_KeyFinder#90]
Maybe this is an issue affecting the keyfinder library and not the gui, in which case I kindly ask you to move this thread.

When analyzing ogg files and choosing to have the key written to the 'comment' tag, keyfinder actually writes to the 'description' tag.  Also, the 'description' tag appears under the 'comment' column in the batch window (so I guess that this might be intended). 
If so, I don't see any reason for this, as other programs use the 'comment' tag to write comments (at least Windows Media Player and Traktor Pro).

**Comment by ibsh** [comment]
This is intended; I can't remember why but I think it was to do with a particular playback app. I thought it was for Traktor, actually, maybe for FLACs, which use Vorbis tags? Been a long while since I've looked.
