### ISSUE TITLE
Language option is missing!

### ISSUE THREAD

**Issue by Patrik356b** [ibsh/is_KeyFinder#92]
There should be a way to override the locale setting in windows.

I'm using English language in all other software but my locale is "SE/SV - Sweden/Swedish"

**Comment by ibsh** [comment]
Won't fix

**Comment by Patrik356b** [comment]
Any reason why?

**Comment by ibsh** [comment]
Yeah, I disagree with the premise :)
I also don't work on Windows anymore, so I'm not sure what the standard behaviour is there. Anyone who does is welcome to make the change.

**Comment by ibsh** [comment]
It feels more like a bug than a missing feature in any case: if you work in English on all your other apps, that's presumably not because they all offer a way to override the locale setting, right?

**Comment by Patrik356b** [comment]
it's a 50/50 thing actually. Some only have english, while others have alot of languages where i just pick english to make it consistent.
