### ISSUE TITLE
Exception: Insufficient low-end resolution

### ISSUE THREAD

**Issue by whobutsb** [ibsh/is_KeyFinder#93]
Hello, whenever I try to key my tracks I get the error: Exception: Insufficient low-end resolution for every track.  I'm using the latest version of Keyfinder, and this is the case for every track.  95% of the tracks i'm trying to key are 320kbs as well.

**Comment by ibsh** [comment]
Make sure you haven't changed any advanced preferences. Hit the reset to
default button.

**Comment by whobutsb** [comment]
Thank you!  That was the issue.
