### ISSUE TITLE
[RFE] highlight compatible tracks

### ISSUE THREAD

**Issue by thoraxe** [ibsh/is_KeyFinder#94]
Rapid Evolution (https://github.com/djqualia/RapidEvolution3) has a feature where it will show compatible tracks. It's also written in Java.

I realize saying "oh it's Java - just patch it in" is super ridiculous, but it would be nice if selecting a track that has been analyzed would highlight compatible tracks automatically.

**Comment by ibsh** [comment]
KeyFinder isn't written in Java, so it's slightly more super ridiculous than you imagine.

In any case, KeyFinder is intended to be a workflow tool, not to be used "at runtime" if you will. So this is beyond its scope.

**Comment by thoraxe** [comment]
Sorry, late night. I don't know why I thought this was Java. 

In any case, can you describe your thoughts on workflow? I actually was not planning to use it in real time.

I am thinking something like:
Given a pile of tracks I think would make a good set
Roughly order them the way I think will work
Load them, in order, into Keyfinder
Click through and verify compatibility 

For a mix planner like myself, I would basically have to do all of the last part manually, referencing something like the Camelot wheel (or other chart) for each track. 

Does that make more sense? Maybe you have a suggestion for something I'm overlooking or over thinking?

**Comment by ibsh** [comment]
If you alter the preferences to write the Camelot codes or Open Key Notation or similar (check the FAQ if you don't know how), then you can write the results to your files' metadata when you first get them, and use any other tool to check compatibility at any time thereafter.

My thoughts on workflow are, you should only ever use KeyFinder once for each track you own. After that it should be up to your player or playlister to read from the file tags and help you figure everything out.

**Comment by thoraxe** [comment]
Sounds good. I haven't found any tool specifically that checks compatibility. I know that Mixxx is supposed to be able to, but I haven't deeply looked into it yet. Rapid Evolution was supposed to do both (analyze and suggest) but the latest beta is fairly broken and the project seems to have been abandoned.

Unfortunately I just have two ancient CDJ-800 (not even Mark II) and a non-digital Behringer mixer, so it's a lot of manual labor over here right now :)

Thanks for the suggestions!
