### ISSUE TITLE
App crash on Windows 8

### ISSUE THREAD

**Issue by gamerboy** [ibsh/is_KeyFinder#96]
KeyFinder is not starting. Please, help me!

This is the content of the log file

```
2015-04-13 19:01:30.374 Warning: QMutex: destroying locked mutex (thread\qmutex.cpp:194)
2015-04-13 19:01:30.425 Warning: QWaitCondition: Destroyed while threads are still waiting (thread\qwaitcondition_win.cpp:155)
```

My config: Microsoft Windows 8, Antivirus: AVG free edition, Firewall: Outpost Pro

Thank you.

**Comment by ibsh** [comment]
Sorry, I don't have the resources to support Windows at present.

**Comment by gamerboy** [comment]
Ok, i will use my Mac.

Thank you.

On Mon, Apr 13, 2015 at 7:22 PM, ibsh <notifications@github.com> wrote:

> Sorry, I don't have the resources to support Windows at present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ibsh/is_KeyFinder/issues/96#issuecomment-92434368>.
>



-- 
 *Prima di stampare questa e-mail, verifica che sia davvero necessario*
