### ISSUE TITLE
Tag Writing

### ISSUE THREAD

**Issue by Pau6532** [ibsh/is_KeyFinder#97]
Hi,

Since updating iTunes, OS etc. I can no longer update my tags, even when doing the manual write key to files. Is this a known issue and being sorted out at the moment? Or am I the only user with current problem

Cheers
Paul

**Comment by ibsh** [comment]
Yours is the only report. Please only reopen this ticket if you have specific helpful evidence that might help me repro or track this down.

**Comment by Pau6532** [comment]
I can't give you any steps on how to reproduce as all I do is open the app, choose an itunes playlist and everything is labelled as N/A. I then hit run batch analysis and once analyzed it does not write automatically or manually
Date: Thu, 3 Dec 2015 09:40:37 -0800
