### ISSUE TITLE
Crash on OS X 10.8.5 when dragging FLAC file to the GUI

### ISSUE THREAD

**Issue by sch4llfl3g3l** [ibsh/is_KeyFinder#99]
On OS X 10.8.5 there also seems to be a problem with FLAC files. Immediate crash when dragging them to the GUI. In this case i have no clue what the error log means - no hint to a single library or sth. like that. EXC_I386_GPFLT is a general x86 protection fault … Log file is attached.
[KeyFinder_2016-01-14-142233_localhost.crash.zip](https://github.com/ibsh/is_KeyFinder/files/90473/KeyFinder_2016-01-14-142233_localhost.crash.zip)

**Comment by ibsh** [comment]
Please try out v2.2, released today. It may fix this crash.
